"""
Precompute all-pairs shortest-time paths for the Newtownards road network,
augmented with external census-area nodes.

External nodes (DEA/SDZ centroids from build_census_zones.py) are added to the
routing graph using OSRM-derived directed edges from build_external_links.py.
The paths cache covers all nodes: internal road nodes + external zone nodes.

OD pair filtering:
  - External→external pairs only allowed if in the through-route allowlist
    (auto-generated by build_external_links.py from OSRM routing checks).
  - All internal↔internal, internal↔external, external↔internal pairs included.

Probit noise is applied per-edge to ALL edges (road and external), but with a
length-dependent gain (see PROBIT_LL_SIGMA / routing_config.py): short legs keep the
multiplicative log-normal perturbation, while long legs (notably the single-edge
external↔boundary legs) have their noise saturate to a fixed absolute sigma. This
stops a long X→B leg's ±CV multiplicative swing from swamping the few-minute
differences between competing boundary entries — boundary node selection for each
external→internal OD pair is then driven by real time differences, not noise.

Run this once after any change to:
  - The road network (build_network.py / edit_network.py)
  - External links (build_external_links.py)
  - HIGHWAY_COST_FACTOR values
  - N_PASSES, PROBIT_CV, or PROBIT_LL_SIGMA
"""

import json, math, time, os
from multiprocessing import Pool
import numpy as np
import osmnx as ox
import pyproj
from scipy.sparse import csr_matrix, coo_matrix
from scipy.sparse.csgraph import dijkstra

from routing_config import HIGHWAY_COST_FACTOR, PROBIT_CV, PROBIT_LL_SIGMA
from model import paths_cache_signature

# Routing graph + weights are the dead-end-reduced artifacts from reduce_deadends.py
# (run after build_demographics.py, before this script). See CLAUDE.md "Dead-end reduction".
CONS_GRAPH        = "simulation/newtownards_reduced.graphml"
WEIGHTS_FILE      = "simulation/node_weights_reduced.json"
CENSUS_ZONES_FILE = "data/census_zones.json"
EXTERNAL_LINKS    = "data/external_links.json"
PATHS_CACHE       = "simulation/newtownards_paths.npz"
N_PASSES          = 25       # stochastic Dijkstra passes for probit loading
# PROBIT_CV / PROBIT_LL_SIGMA imported from routing_config (paths-cache signature inputs)
RANDOM_SEED       = 42
MAX_HOPS          = 120      # path-trace hop limit per OD pair per pass
N_WORKERS         = 1        # parallel worker processes (increase if RAM allows)

# ── Module-level globals shared with worker processes (fork-inherited) ─────────
# Set in main body before Pool creation; workers read them as copy-on-write.
_g_all_data_arr = None
_g_all_rows_arr = None
_g_all_cols_arr = None
_g_probit_w     = None   # per-edge length-dependent noise gain (constant across passes)
_g_n            = None
_g_PROBIT_CV    = None
_g_N_PASSES     = None
_g_src_groups   = None   # {src_i: {'pks': list, 'pks_np': np.int32, 'dsts': list}}
_g_edge_to_link = None
_g_edge_cost    = None
_g_od_k1_flat   = None
_g_od_k1_off    = None
_g_od_k1_dist   = None
_g_n_pairs      = None
_g_N_links      = None


def _run_pass(args):
    """Worker: one stochastic probit pass. Reads module globals (fork-inherited)."""
    pass_idx, seed = args
    t_pass = time.time()

    rng    = np.random.default_rng(seed)
    eps    = rng.normal(0.0, _g_PROBIT_CV, size=len(_g_all_data_arr))
    # Length-scaled probit noise: gain _g_probit_w damps eps on long legs so the
    # perturbation saturates to an absolute sigma (PROBIT_LL_SIGMA) instead of a
    # multiplicative one. w→1 for short legs (unchanged), w→0 for long legs.
    data_p = _g_all_data_arr * np.exp(eps * _g_probit_w)
    adj_p  = csr_matrix((data_p, (_g_all_rows_arr, _g_all_cols_arr)), shape=(_g_n, _g_n))
    _, pred_p = dijkstra(adj_p, directed=True, return_predecessors=True)
    del data_p, adj_p

    dist_accum_pass   = np.zeros(_g_n_pairs, dtype=np.float64)
    n_fallbacks_pass  = 0
    n_hop_limit_pass  = 0
    pass_pairs_chunks = []
    pass_links_chunks = []

    for src_i, grp in _g_src_groups.items():
        pair_ks    = grp['pks']
        pair_ks_np = grp['pks_np']   # int32 numpy array, same values as pair_ks
        dsts       = grp['dsts']
        n_s        = len(pair_ks)

        cur    = np.array(dsts, dtype=np.int32)
        done   = np.zeros(n_s, dtype=bool)
        fallbk = np.zeros(n_s, dtype=bool)
        pc     = np.zeros(n_s, dtype=np.float64)

        for _ in range(MAX_HOPS):
            at_src = ~done & (cur == src_i)
            done  |= at_src
            if done.all():
                break

            active = ~done
            prev   = pred_p[src_i, cur]

            dead    = active & (prev < 0)
            fallbk |= dead
            done   |= dead

            active_ok = active & ~dead
            if not active_ok.any():
                break

            aok      = np.where(active_ok)[0]
            prev_aok = prev[aok]
            cur_aok  = cur[aok]
            li_aok   = _g_edge_to_link[prev_aok, cur_aok]
            cost_aok = _g_edge_cost[prev_aok, cur_aok]

            # Vectorised cost accumulation
            np.add.at(pc, aok, cost_aok.astype(np.float64))

            # Vectorised road-link hit collection
            road_mask = li_aok >= 0
            if road_mask.any():
                valid_aok = aok[road_mask]
                pass_pairs_chunks.append(pair_ks_np[valid_aok])
                pass_links_chunks.append(li_aok[road_mask])

            cur[active_ok] = prev[active_ok]
        else:
            # for-loop exhausted all MAX_HOPS without done.all() — limit reached
            n_hop_limit_pass += 1

        # Vectorised distance accumulation for non-fallback pairs
        non_fb = ~fallbk
        if non_fb.any():
            np.add.at(dist_accum_pass, pair_ks_np[non_fb], pc[non_fb])

        # Fallback: substitute k=1 path for pairs that lost their predecessor
        fb_indices = np.where(fallbk)[0]
        for m in fb_indices:
            pk = int(pair_ks_np[m])
            n_fallbacks_pass += 1
            dist_accum_pass[pk] += _g_od_k1_dist[pk]
            _s, _e = int(_g_od_k1_off[pk]), int(_g_od_k1_off[pk + 1])
            if _e > _s:
                pass_pairs_chunks.append(np.full(_e - _s, pk, dtype=np.int32))
                pass_links_chunks.append(_g_od_k1_flat[_s:_e])

    del pred_p

    if pass_pairs_chunks:
        pp = np.concatenate(pass_pairs_chunks)
        pl = np.concatenate(pass_links_chunks)
    else:
        pp = np.empty(0, dtype=np.int32)
        pl = np.empty(0, dtype=np.int32)

    elapsed = time.time() - t_pass
    suffix  = f", {n_hop_limit_pass} hop-limit hit" if n_hop_limit_pass else ""
    print(f"  Pass {pass_idx + 1}/{_g_N_PASSES} done in {elapsed:.1f}s"
          f"  ({n_fallbacks_pass:,} fallbacks{suffix})", flush=True)
    return pp, pl, dist_accum_pass, n_fallbacks_pass


# ── Load graph ────────────────────────────────────────────────────────────────

print("Loading graph …")
G = ox.load_graphml(CONS_GRAPH)
G = ox.routing.add_edge_speeds(G)
G = ox.routing.add_edge_travel_times(G)
road_node_ids = list(G.nodes())
n_road = len(road_node_ids)
print(f"  {n_road} road nodes  {G.number_of_edges()} edges")

# Build OSM node ID → consolidated node ID mapping.
# boundary_node_ids from external_links.json are raw OSM IDs (matched by OSRM);
# the consolidated graph uses renumbered IDs, so we need this to add external edges.
_osm_to_cons = {}
for _cid, _cdata in G.nodes(data=True):
    _osmids = _cdata.get("osmid_original")
    if _osmids is None:
        continue
    if isinstance(_osmids, list):
        for _oid in _osmids:
            _osm_to_cons[int(_oid)] = _cid
    else:
        _osm_to_cons[int(_osmids)] = _cid

# ── Load external links ────────────────────────────────────────────────────────

if not os.path.exists(EXTERNAL_LINKS):
    print(f"ERROR: {EXTERNAL_LINKS} not found. Run build_external_links.py first.")
    raise SystemExit(1)

print("Loading external links …")
with open(EXTERNAL_LINKS) as f:
    ext_data = json.load(f)

ext_boundary_links      = ext_data["ext_boundary_links"]
bnd_external_links      = ext_data["bnd_external_links"]
boundary_boundary_links = ext_data["boundary_boundary_links"]
allowed_through_pairs   = {k: set(v) for k, v in ext_data["allowed_through_pairs"].items()}
_EMPTY_SET = frozenset()
boundary_node_ids = set(ext_data["boundary_node_ids"])

print(f"  {len(ext_boundary_links)} X→B links")
print(f"  {len(bnd_external_links)} B→X links")
print(f"  {len(boundary_boundary_links)} boundary→boundary shortcuts")
print(f"  {len(allowed_through_pairs)} allowed through-route pairs")

# ── Load external node positions ───────────────────────────────────────────────

with open(CENSUS_ZONES_FILE) as f:
    census_zones = json.load(f)

to_utm = pyproj.Transformer.from_crs("EPSG:4326", "EPSG:32630", always_xy=True)

ext_node_list = census_zones["external_nodes"]
ext_id_to_utm = {}
for ext in ext_node_list:
    utm_x, utm_y = to_utm.transform(ext["centroid_lon"], ext["centroid_lat"])
    ext_id_to_utm[ext["id"]] = (utm_x, utm_y)

# External node IDs used in ext_boundary_links and bnd_external_links
ext_ids_used = set()
for lnk in ext_boundary_links:
    ext_ids_used.add(lnk["from_ext"])
for lnk in bnd_external_links:
    ext_ids_used.add(lnk["to_ext"])

ext_node_ids = sorted(ext_ids_used)
n_ext = len(ext_node_ids)
print(f"\n{n_ext} external nodes appear in link data")

# ── Build unified node list ────────────────────────────────────────────────────

# Road nodes come first (indices 0..n_road-1), then external nodes
all_node_ids = road_node_ids + ext_node_ids
n = len(all_node_ids)
node_to_idx = {nid: i for i, nid in enumerate(all_node_ids)}
print(f"Total nodes: {n} ({n_road} road + {n_ext} external)")

# ── Build sparse adjacency matrix ─────────────────────────────────────────────

print("Building sparse adjacency matrix …")
rows, cols, data_road = [], [], []
link_list   = []
link_to_idx = {}

for u, v, edata in G.edges(data=True):
    ht = edata.get("highway", "unclassified")
    if isinstance(ht, list):
        ht = ht[0]
    factor = HIGHWAY_COST_FACTOR.get(ht, 1.0)
    cost = float(edata.get("travel_time", 1.0)) * factor
    i, j = node_to_idx[u], node_to_idx[v]
    rows.append(i); cols.append(j); data_road.append(cost)
    lnk = (u, v)
    if lnk not in link_to_idx:
        link_to_idx[lnk] = len(link_list)
        link_list.append(lnk)

N_links = len(link_list)
print(f"  {N_links} road links")

# External edges (X→B, B→X, boundary→boundary exterior shortcuts)
# Deduplicate by (i, j) keeping minimum duration.
_ext_edge_min = {}

for lnk in ext_boundary_links:
    xi = node_to_idx.get(lnk["from_ext"])
    b_cons = _osm_to_cons.get(lnk["to_boundary"])
    bi = node_to_idx.get(b_cons) if b_cons is not None else None
    if xi is not None and bi is not None:
        key = (xi, bi)
        d = float(lnk["duration_s"])
        if key not in _ext_edge_min or d < _ext_edge_min[key]:
            _ext_edge_min[key] = d

for lnk in bnd_external_links:
    b_cons = _osm_to_cons.get(lnk["from_boundary"])
    bi = node_to_idx.get(b_cons) if b_cons is not None else None
    xi = node_to_idx.get(lnk["to_ext"])
    if bi is not None and xi is not None:
        key = (bi, xi)
        d = float(lnk["duration_s"])
        if key not in _ext_edge_min or d < _ext_edge_min[key]:
            _ext_edge_min[key] = d

for lnk in boundary_boundary_links:
    f_cons = _osm_to_cons.get(lnk["from"])
    t_cons = _osm_to_cons.get(lnk["to"])
    i = node_to_idx.get(f_cons) if f_cons is not None else None
    j = node_to_idx.get(t_cons) if t_cons is not None else None
    if i is not None and j is not None:
        key = (i, j)
        d = float(lnk["duration_s"])
        if key not in _ext_edge_min or d < _ext_edge_min[key]:
            _ext_edge_min[key] = d

rows_ext = [i for i, j in _ext_edge_min]
cols_ext = [j for i, j in _ext_edge_min]
data_ext = [d for d in _ext_edge_min.values()]
print(f"  {len(data_ext)} external edges after dedup (X↔B + boundary shortcuts)")

# Combined adjacency matrix
all_rows = rows + rows_ext
all_cols = cols + cols_ext
all_data = data_road + data_ext
adj = csr_matrix((all_data, (all_rows, all_cols)), shape=(n, n))

# ── Dense lookup tables (road links only) ─────────────────────────────────────

print("Building edge lookup tables …")
edge_to_link = np.full((n, n), -1, dtype=np.int32)
edge_cost    = np.zeros((n, n), dtype=np.float32)

for (u, v), li in link_to_idx.items():
    i, j = node_to_idx[u], node_to_idx[v]
    edge_to_link[i, j] = li

for row_i, col_i, cost_i in zip(rows, cols, data_road):
    if edge_cost[row_i, col_i] == 0.0 or cost_i < edge_cost[row_i, col_i]:
        edge_cost[row_i, col_i] = float(cost_i)

# External edges also need costs in edge_cost so probit path tracing
# accumulates the correct duration for boundary→external legs.
for (ei, ej), d in _ext_edge_min.items():
    if edge_cost[ei, ej] == 0.0:
        edge_cost[ei, ej] = float(d)

# ── k=1 all-pairs Dijkstra ─────────────────────────────────────────────────────

print("Running k=1 Dijkstra …")
t0 = time.time()
dist_matrix, predecessors = dijkstra(adj, directed=True, return_predecessors=True)
print(f"  Done in {time.time()-t0:.1f}s")

# ── Build OD pair list ─────────────────────────────────────────────────────────

print("Building OD pair list …")
t0 = time.time()

ext_idx_set = {node_to_idx[nid] for nid in ext_node_ids}

od_src_list = []
od_dst_list = []
od_k1_links = []
od_k1_dist  = []

for src_i, src_nid in enumerate(all_node_ids):
    src_is_ext = src_i in ext_idx_set

    for dst_i, dst_nid in enumerate(all_node_ids):
        if dst_i == src_i:
            continue

        # External→external: only allowed through-route pairs
        if src_is_ext and dst_i in ext_idx_set:
            if dst_nid not in allowed_through_pairs.get(src_nid, _EMPTY_SET):
                continue

        d_net = dist_matrix[src_i, dst_i]
        if not math.isfinite(d_net) or d_net < 1.0:
            continue

        # Trace k=1 path
        path_links = []
        cur = dst_i
        while cur != src_i:
            prev = predecessors[src_i, cur]
            if prev < 0:
                break
            li = edge_to_link[prev, cur]
            if li >= 0:
                path_links.append(li)
            cur = prev
        if not path_links and src_i not in ext_idx_set and dst_i not in ext_idx_set:
            # Internal-internal pair with no road links traced — skip
            continue
        path_links.reverse()

        od_src_list.append(src_i)
        od_dst_list.append(dst_i)
        od_k1_links.append(path_links)
        od_k1_dist.append(d_net)

    if (src_i + 1) % 100 == 0:
        print(f"  {src_i + 1}/{n} nodes  ({time.time()-t0:.1f}s)  {len(od_src_list):,} pairs")

n_pairs = len(od_src_list)
print(f"  {n_pairs:,} OD pairs  in {time.time()-t0:.1f}s")

# Compact od_k1_links into a flat numpy int32 ragged array.
_k1_lengths = np.array([len(p) for p in od_k1_links], dtype=np.int32)
od_k1_off   = np.zeros(n_pairs + 1, dtype=np.int32)
np.cumsum(_k1_lengths, out=od_k1_off[1:])
od_k1_flat  = np.empty(int(od_k1_off[-1]), dtype=np.int32)
for _i, _p in enumerate(od_k1_links):
    od_k1_flat[od_k1_off[_i]:od_k1_off[_i + 1]] = _p
del od_k1_links, _k1_lengths

del dist_matrix, predecessors

# ── Group OD pairs by source ───────────────────────────────────────────────────

src_groups = {}
for k, (si, di) in enumerate(zip(od_src_list, od_dst_list)):
    if si not in src_groups:
        src_groups[si] = {'pks': [], 'dsts': []}
    src_groups[si]['pks'].append(k)
    src_groups[si]['dsts'].append(di)

# Pre-compute numpy int32 pair-index arrays for vectorised path tracing.
for grp in src_groups.values():
    grp['pks_np'] = np.array(grp['pks'], dtype=np.int32)

# ── Set worker globals ─────────────────────────────────────────────────────────
# These must be set before Pool creation so fork-spawned workers inherit them
# via copy-on-write — no large-array pickling required.

_g_all_data_arr = np.array(all_data, dtype=np.float64)
_g_all_rows_arr = np.array(all_rows, dtype=np.int32)
_g_all_cols_arr = np.array(all_cols, dtype=np.int32)
_g_n            = n
_g_PROBIT_CV    = PROBIT_CV
# Per-edge length-dependent noise gain: w = σ_ll / (σ_ll + CV·cost), in (0,1].
# w→1 for short edges (multiplicative noise preserved); w→σ_ll/(CV·cost) for long
# edges (noise saturates to an absolute N(0,σ_ll) offset). Constant across passes.
_g_probit_w     = PROBIT_LL_SIGMA / (PROBIT_LL_SIGMA + PROBIT_CV * _g_all_data_arr)
_g_N_PASSES     = N_PASSES
_g_src_groups   = src_groups
_g_edge_to_link = edge_to_link
_g_edge_cost    = edge_cost
_g_od_k1_flat   = od_k1_flat
_g_od_k1_off    = od_k1_off
_g_od_k1_dist   = np.array(od_k1_dist, dtype=np.float64)
_g_n_pairs      = n_pairs
_g_N_links      = N_links

# ── Stochastic probit passes ───────────────────────────────────────────────────
# Results are accumulated incrementally so only one pass worth of pair/link
# arrays (~200 MB) is held in memory at a time, regardless of N_WORKERS.

n_workers = min(N_WORKERS, N_PASSES)
print(f"\nRunning {N_PASSES} stochastic probit passes "
      f"(CV={PROBIT_CV}, seed={RANDOM_SEED}, workers={n_workers}) …")
t0    = time.time()
rng   = np.random.default_rng(seed=RANDOM_SEED)
seeds = rng.integers(0, 2**31, size=N_PASSES)
tasks = list(zip(range(N_PASSES), seeds.tolist()))

dist_accum  = np.zeros(n_pairs, dtype=np.float64)
hit_sparse  = csr_matrix((n_pairs, N_links), dtype=np.float32)
n_fallbacks = 0

def _accumulate(pp, pl, dist_pass, nf):
    global dist_accum, hit_sparse, n_fallbacks
    dist_accum += dist_pass
    n_fallbacks += nf
    if len(pp):
        _m = coo_matrix(
            (np.ones(len(pp), dtype=np.float32), (pp, pl)),
            shape=(n_pairs, N_links),
        ).tocsr()
        hit_sparse = hit_sparse + _m

if n_workers == 1:
    # Serial path: call worker directly, no subprocess or IPC overhead.
    for task in tasks:
        pp, pl, dist_pass, nf = _run_pass(task)
        _accumulate(pp, pl, dist_pass, nf)
        del pp, pl, dist_pass
else:
    # Parallel path: imap streams results back one at a time so only one
    # pass result is held in memory while the next batch is in flight.
    with Pool(processes=n_workers) as pool:
        for pp, pl, dist_pass, nf in pool.imap(_run_pass, tasks):
            _accumulate(pp, pl, dist_pass, nf)
            del pp, pl, dist_pass

print(f"  All passes done in {time.time()-t0:.1f}s  ({n_fallbacks:,} pair-pass fallbacks)")

# ── Build output arrays ────────────────────────────────────────────────────────

print("Building output arrays …")
od_dist_out = (dist_accum / N_PASSES).astype(np.float32)

_coo         = hit_sparse.tocoo()
pair_idx_arr = _coo.row.astype(np.int32)
link_idx_arr = _coo.col.astype(np.int32)
vals_arr     = _coo.data
del hit_sparse, _coo
link_weight_arr = vals_arr / N_PASSES
del vals_arr

sort_order      = np.argsort(pair_idx_arr, kind='stable')
pair_idx_arr    = pair_idx_arr[sort_order]
link_idx_arr    = link_idx_arr[sort_order]
link_weight_arr = link_weight_arr[sort_order]
del sort_order

n_entries   = len(pair_idx_arr)
mean_lpp    = n_entries / max(n_pairs, 1)
print(f"  {n_pairs:,} OD pairs  {n_entries:,} entries  mean {mean_lpp:.1f} links/pair")

# ── Save ──────────────────────────────────────────────────────────────────────

print("Saving cache …")
# Stamp a signature of the inputs (graph, external links, cost factors) so
# tune_assignment.py / build_assignment.py can detect a stale cache loudly.
_sig = paths_cache_signature()
np.savez_compressed(
    PATHS_CACHE,
    node_ids        = np.array(all_node_ids, dtype=object),
    od_src          = np.array(od_src_list,  dtype=np.int32),
    od_dst          = np.array(od_dst_list,  dtype=np.int32),
    od_dist         = od_dist_out,
    pair_idx        = pair_idx_arr,
    link_idx        = link_idx_arr,
    link_weight     = link_weight_arr,
    link_u          = np.array([u for u, v in link_list], dtype=np.int64),
    link_v          = np.array([v for u, v in link_list], dtype=np.int64),
    probit_n_passes = np.int32(N_PASSES),
    probit_cv       = np.float32(PROBIT_CV),
    probit_ll_sigma = np.float32(PROBIT_LL_SIGMA),
    src_graph_sha1     = np.array(_sig["src_graph_sha1"]),
    src_extlinks_sha1  = np.array(_sig["src_extlinks_sha1"]),
    src_cost_factor    = np.array(_sig["src_cost_factor"]),
    src_probit_cv      = np.array(_sig["src_probit_cv"]),
    src_probit_ll_sigma = np.array(_sig["src_probit_ll_sigma"]),
)
size_mb = os.path.getsize(PATHS_CACHE) / 1e6
print(f"Saved: {PATHS_CACHE}  ({size_mb:.1f} MB)")
print(f"  {n_pairs:,} OD pairs  {n_entries:,} entries  "
      f"{N_PASSES} passes  CV={PROBIT_CV}  LL_SIGMA={PROBIT_LL_SIGMA:g}s")
print(f"  {n_road} road nodes + {n_ext} external nodes = {n} total")
