"""
Precompute all-pairs shortest-time paths for the Newtownards road network,
augmented with external census-area nodes.

External nodes (DEA/SDZ centroids from build_census_zones.py) are added to the
routing graph using OSRM-derived directed edges from build_external_links.py.
The paths cache covers all nodes: internal road nodes + external zone nodes.

OD pair filtering:
  - External→external pairs only allowed if in the through-route allowlist
    (auto-generated by build_external_links.py from OSRM routing checks).
  - All internal↔internal, internal↔external, external↔internal pairs included.

External→boundary edges carry fixed weight (no probit noise) so that boundary
node selection for each external→internal OD pair varies via probit on the
internal portion of the route.

Run this once after any change to:
  - The road network (build_network.py / edit_network.py)
  - External links (build_external_links.py)
  - HIGHWAY_COST_FACTOR values
  - N_PASSES or PROBIT_CV
"""

import array as _array_mod
import json, math, time, os
import numpy as np
import osmnx as ox
import pyproj
from scipy.sparse import csr_matrix, coo_matrix
from scipy.sparse.csgraph import dijkstra

CONS_GRAPH        = "simulation/newtownards_consolidated.graphml"
WEIGHTS_FILE      = "simulation/node_weights.json"
CENSUS_ZONES_FILE = "data/census_zones.json"
EXTERNAL_LINKS    = "data/external_links.json"
PATHS_CACHE       = "simulation/newtownards_paths.npz"
N_PASSES          = 25       # stochastic Dijkstra passes for probit loading
PROBIT_CV         = 0.25     # log-normal noise CV applied to road edge costs
RANDOM_SEED       = 42

HIGHWAY_COST_FACTOR = {
    "trunk":         0.67,
    "trunk_link":    0.67,
    "primary":       0.67,
    "primary_link":  0.67,
    "secondary":     1.0,
    "tertiary":      1.0,
    "tertiary_link": 1.0,
    "residential":   1.2,
    "unclassified":  1.2,
    "living_street": 1.2,
}

# ── Load graph ────────────────────────────────────────────────────────────────

print("Loading graph …")
G = ox.load_graphml(CONS_GRAPH)
G = ox.routing.add_edge_speeds(G)
G = ox.routing.add_edge_travel_times(G)
road_node_ids = list(G.nodes())
n_road = len(road_node_ids)
print(f"  {n_road} road nodes  {G.number_of_edges()} edges")

# Build OSM node ID → consolidated node ID mapping.
# boundary_node_ids from external_links.json are raw OSM IDs (matched by OSRM);
# the consolidated graph uses renumbered IDs, so we need this to add external edges.
_osm_to_cons = {}
for _cid, _cdata in G.nodes(data=True):
    _osmids = _cdata.get("osmid_original")
    if _osmids is None:
        continue
    if isinstance(_osmids, list):
        for _oid in _osmids:
            _osm_to_cons[int(_oid)] = _cid
    else:
        _osm_to_cons[int(_osmids)] = _cid

# ── Load external links ────────────────────────────────────────────────────────

if not os.path.exists(EXTERNAL_LINKS):
    print(f"ERROR: {EXTERNAL_LINKS} not found. Run build_external_links.py first.")
    raise SystemExit(1)

print("Loading external links …")
with open(EXTERNAL_LINKS) as f:
    ext_data = json.load(f)

ext_boundary_links     = ext_data["ext_boundary_links"]      # X→B
bnd_external_links     = ext_data["bnd_external_links"]      # B→X
boundary_boundary_links = ext_data["boundary_boundary_links"] # B1→B2 exterior
allowed_through_pairs  = {k: set(v) for k, v in ext_data["allowed_through_pairs"].items()}
_EMPTY_SET = frozenset()
boundary_node_ids      = set(ext_data["boundary_node_ids"])

print(f"  {len(ext_boundary_links)} X→B links")
print(f"  {len(bnd_external_links)} B→X links")
print(f"  {len(boundary_boundary_links)} boundary→boundary shortcuts")
print(f"  {len(allowed_through_pairs)} allowed through-route pairs")

# ── Load external node positions ───────────────────────────────────────────────

with open(CENSUS_ZONES_FILE) as f:
    census_zones = json.load(f)

to_utm = pyproj.Transformer.from_crs("EPSG:4326", "EPSG:32630", always_xy=True)

ext_node_list = census_zones["external_nodes"]
ext_id_to_utm = {}
for ext in ext_node_list:
    utm_x, utm_y = to_utm.transform(ext["centroid_lon"], ext["centroid_lat"])
    ext_id_to_utm[ext["id"]] = (utm_x, utm_y)

# External node IDs used in ext_boundary_links and bnd_external_links
ext_ids_used = set()
for lnk in ext_boundary_links:
    ext_ids_used.add(lnk["from_ext"])
for lnk in bnd_external_links:
    ext_ids_used.add(lnk["to_ext"])

ext_node_ids = sorted(ext_ids_used)
n_ext = len(ext_node_ids)
print(f"\n{n_ext} external nodes appear in link data")

# ── Build unified node list ────────────────────────────────────────────────────

# Road nodes come first (indices 0..n_road-1), then external nodes
all_node_ids = road_node_ids + ext_node_ids
n = len(all_node_ids)
node_to_idx = {nid: i for i, nid in enumerate(all_node_ids)}
print(f"Total nodes: {n} ({n_road} road + {n_ext} external)")

# ── Build sparse adjacency matrix ─────────────────────────────────────────────

print("Building sparse adjacency matrix …")
rows, cols, data_road = [], [], []
link_list   = []
link_to_idx = {}

for u, v, edata in G.edges(data=True):
    ht = edata.get("highway", "unclassified")
    if isinstance(ht, list):
        ht = ht[0]
    factor = HIGHWAY_COST_FACTOR.get(ht, 1.0)
    cost = float(edata.get("travel_time", 1.0)) * factor
    i, j = node_to_idx[u], node_to_idx[v]
    rows.append(i); cols.append(j); data_road.append(cost)
    lnk = (u, v)
    if lnk not in link_to_idx:
        link_to_idx[lnk] = len(link_list)
        link_list.append(lnk)

N_links = len(link_list)
print(f"  {N_links} road links")

# External edges (X→B, B→X, boundary→boundary exterior shortcuts)
# These are NOT added to link_list (they don't appear in flow output),
# but ARE included in the adjacency matrix for routing.
# Deduplicate by (i, j) keeping minimum duration: if two OSM boundary nodes
# B1 and B2 were consolidated into the same node C, both X→B1 and X→B2
# translate to X→C, and csr_matrix would otherwise sum their durations.
_ext_edge_min = {}   # (i, j) → min duration_s

for lnk in ext_boundary_links:
    xi = node_to_idx.get(lnk["from_ext"])
    b_cons = _osm_to_cons.get(lnk["to_boundary"])
    bi = node_to_idx.get(b_cons) if b_cons is not None else None
    if xi is not None and bi is not None:
        key = (xi, bi)
        d = float(lnk["duration_s"])
        if key not in _ext_edge_min or d < _ext_edge_min[key]:
            _ext_edge_min[key] = d

for lnk in bnd_external_links:
    b_cons = _osm_to_cons.get(lnk["from_boundary"])
    bi = node_to_idx.get(b_cons) if b_cons is not None else None
    xi = node_to_idx.get(lnk["to_ext"])
    if bi is not None and xi is not None:
        key = (bi, xi)
        d = float(lnk["duration_s"])
        if key not in _ext_edge_min or d < _ext_edge_min[key]:
            _ext_edge_min[key] = d

for lnk in boundary_boundary_links:
    f_cons = _osm_to_cons.get(lnk["from"])
    t_cons = _osm_to_cons.get(lnk["to"])
    i = node_to_idx.get(f_cons) if f_cons is not None else None
    j = node_to_idx.get(t_cons) if t_cons is not None else None
    if i is not None and j is not None:
        key = (i, j)
        d = float(lnk["duration_s"])
        if key not in _ext_edge_min or d < _ext_edge_min[key]:
            _ext_edge_min[key] = d

rows_ext = [i for i, j in _ext_edge_min]
cols_ext = [j for i, j in _ext_edge_min]
data_ext = [d for d in _ext_edge_min.values()]
print(f"  {len(data_ext)} external edges after dedup (X↔B + boundary shortcuts)")

# Combined adjacency matrix
all_rows = rows + rows_ext
all_cols = cols + cols_ext
all_data = data_road + data_ext
adj = csr_matrix((all_data, (all_rows, all_cols)), shape=(n, n))

# ── Dense lookup tables (road links only) ─────────────────────────────────────

print("Building edge lookup tables …")
edge_to_link = np.full((n, n), -1, dtype=np.int32)
edge_cost    = np.zeros((n, n), dtype=np.float32)

for (u, v), li in link_to_idx.items():
    i, j = node_to_idx[u], node_to_idx[v]
    edge_to_link[i, j] = li

for row_i, col_i, cost_i in zip(rows, cols, data_road):
    if edge_cost[row_i, col_i] == 0.0 or cost_i < edge_cost[row_i, col_i]:
        edge_cost[row_i, col_i] = float(cost_i)

# ── k=1 all-pairs Dijkstra ─────────────────────────────────────────────────────

print("Running k=1 Dijkstra …")
t0 = time.time()
dist_matrix, predecessors = dijkstra(adj, directed=True, return_predecessors=True)
print(f"  Done in {time.time()-t0:.1f}s")

# ── Build OD pair list ─────────────────────────────────────────────────────────

print("Building OD pair list …")
t0 = time.time()

ext_idx_set = {node_to_idx[nid] for nid in ext_node_ids}

od_src_list = []
od_dst_list = []
od_k1_links = []
od_k1_dist  = []

for src_i, src_nid in enumerate(all_node_ids):
    src_is_ext = src_i in ext_idx_set

    for dst_i, dst_nid in enumerate(all_node_ids):
        if dst_i == src_i:
            continue

        # External→external: only allowed through-route pairs
        if src_is_ext and dst_i in ext_idx_set:
            if dst_nid not in allowed_through_pairs.get(src_nid, _EMPTY_SET):
                continue

        d_net = dist_matrix[src_i, dst_i]
        if not math.isfinite(d_net) or d_net < 1.0:
            continue

        # Trace k=1 path
        path_links = []
        cur = dst_i
        while cur != src_i:
            prev = predecessors[src_i, cur]
            if prev < 0:
                break
            li = edge_to_link[prev, cur]
            if li >= 0:
                path_links.append(li)
            cur = prev
        if not path_links and src_i not in ext_idx_set and dst_i not in ext_idx_set:
            # Internal-internal pair with no road links traced — skip
            continue
        path_links.reverse()

        od_src_list.append(src_i)
        od_dst_list.append(dst_i)
        od_k1_links.append(path_links)
        od_k1_dist.append(d_net)

    if (src_i + 1) % 100 == 0:
        print(f"  {src_i + 1}/{n} nodes  ({time.time()-t0:.1f}s)  {len(od_src_list):,} pairs")

n_pairs = len(od_src_list)
print(f"  {n_pairs:,} OD pairs  in {time.time()-t0:.1f}s")

# Compact od_k1_links (Python list-of-lists, ~700 MB for 1M pairs) into a flat
# numpy int32 ragged array (~80 MB) before memory-intensive pass phase.
_k1_lengths = np.array([len(p) for p in od_k1_links], dtype=np.int32)
od_k1_off   = np.zeros(n_pairs + 1, dtype=np.int32)
np.cumsum(_k1_lengths, out=od_k1_off[1:])
od_k1_flat  = np.empty(int(od_k1_off[-1]), dtype=np.int32)
for _i, _p in enumerate(od_k1_links):
    od_k1_flat[od_k1_off[_i]:od_k1_off[_i + 1]] = _p
del od_k1_links, _k1_lengths

del dist_matrix, predecessors

# ── Group OD pairs by source ───────────────────────────────────────────────────

src_groups = {}
for k, (si, di) in enumerate(zip(od_src_list, od_dst_list)):
    if si not in src_groups:
        src_groups[si] = {'pks': [], 'dsts': []}
    src_groups[si]['pks'].append(k)
    src_groups[si]['dsts'].append(di)

# ── Stochastic probit passes ───────────────────────────────────────────────────
# All edges (road and external) perturbed with log-normal noise each pass.
# External edges carry noise too so boundary node selection varies stochastically
# for external→internal OD pairs with similarly-weighted entry options.

print(f"\nRunning {N_PASSES} stochastic probit passes (CV={PROBIT_CV}, seed={RANDOM_SEED}) …")
t0  = time.time()
rng = np.random.default_rng(seed=RANDOM_SEED)

all_data_arr = np.array(all_data, dtype=np.float64)
all_rows_arr = np.array(all_rows, dtype=np.int32)
all_cols_arr = np.array(all_cols, dtype=np.int32)

# Use a running scipy CSR matrix instead of a Python dict to accumulate hits.
# Python dict with ~20M entries costs ~2.4 GB; CSR costs ~160 MB.
hit_sparse  = csr_matrix((n_pairs, N_links), dtype=np.float32)
dist_accum  = np.zeros(n_pairs, dtype=np.float64)
n_fallbacks = 0

for pass_idx in range(N_PASSES):
    t_pass = time.time()

    eps    = rng.normal(0.0, PROBIT_CV, size=len(all_data_arr))
    data_p = all_data_arr * np.exp(eps)
    adj_p  = csr_matrix((data_p, (all_rows_arr, all_cols_arr)), shape=(n, n))
    _, pred_p = dijkstra(adj_p, directed=True, return_predecessors=True)
    del data_p, adj_p

    # Per-pass hit buffers: array.array stores C ints (4 bytes each) vs
    # Python list-of-ints (~28 bytes each), keeping peak memory low.
    pass_pairs = _array_mod.array('i')
    pass_links = _array_mod.array('i')

    for src_i, grp in src_groups.items():
        pair_ks = grp['pks']
        dsts    = grp['dsts']
        n_s     = len(pair_ks)

        cur    = np.array(dsts, dtype=np.int32)
        done   = np.zeros(n_s, dtype=bool)
        fallbk = np.zeros(n_s, dtype=bool)
        pc     = np.zeros(n_s, dtype=np.float64)

        for _ in range(400):   # extra headroom for longer external paths
            at_src = ~done & (cur == src_i)
            done  |= at_src
            if done.all():
                break

            active = ~done
            prev   = pred_p[src_i, cur]

            dead    = active & (prev < 0)
            fallbk |= dead
            done   |= dead

            active_ok = active & ~dead
            if not active_ok.any():
                break

            aok      = np.where(active_ok)[0]
            prev_aok = prev[aok]
            cur_aok  = cur[aok]
            li_aok   = edge_to_link[prev_aok, cur_aok]
            cost_aok = edge_cost[prev_aok, cur_aok]

            for j in range(len(aok)):
                m  = aok[j]
                li = int(li_aok[j])
                pc[m] += float(cost_aok[j])
                if li >= 0:
                    pass_pairs.append(pair_ks[m])
                    pass_links.append(li)

            cur[active_ok] = prev[active_ok]

        for m in range(n_s):
            pk = pair_ks[m]
            if fallbk[m]:
                n_fallbacks += 1
                dist_accum[pk] += od_k1_dist[pk]
                _s, _e = od_k1_off[pk], od_k1_off[pk + 1]
                for li in od_k1_flat[_s:_e]:
                    pass_pairs.append(pk)
                    pass_links.append(int(li))
            else:
                dist_accum[pk] += pc[m]

    del pred_p

    # Accumulate this pass's hits into the running sparse matrix.
    _n_h = len(pass_pairs)
    _m   = coo_matrix(
        (np.ones(_n_h, dtype=np.float32),
         (np.array(pass_pairs, dtype=np.int32),
          np.array(pass_links,  dtype=np.int32))),
        shape=(n_pairs, N_links),
    ).tocsr()
    hit_sparse = hit_sparse + _m
    del pass_pairs, pass_links, _m

    print(f"  Pass {pass_idx + 1}/{N_PASSES} done in {time.time() - t_pass:.1f}s")

print(f"  All passes done in {time.time()-t0:.1f}s  ({n_fallbacks:,} pair-pass fallbacks)")

# ── Build output arrays ────────────────────────────────────────────────────────

print("Building output arrays …")
od_dist_out = (dist_accum / N_PASSES).astype(np.float32)

_coo         = hit_sparse.tocoo()
pair_idx_arr = _coo.row.astype(np.int32)
link_idx_arr = _coo.col.astype(np.int32)
vals_arr     = _coo.data
del hit_sparse, _coo
link_weight_arr = vals_arr / N_PASSES
del vals_arr

sort_order      = np.argsort(pair_idx_arr, kind='stable')
pair_idx_arr    = pair_idx_arr[sort_order]
link_idx_arr    = link_idx_arr[sort_order]
link_weight_arr = link_weight_arr[sort_order]
del sort_order

n_entries   = len(pair_idx_arr)
mean_lpp    = n_entries / max(n_pairs, 1)
print(f"  {n_pairs:,} OD pairs  {n_entries:,} entries  mean {mean_lpp:.1f} links/pair")

# ── Save ──────────────────────────────────────────────────────────────────────

print("Saving cache …")
np.savez_compressed(
    PATHS_CACHE,
    node_ids        = np.array(all_node_ids, dtype=object),
    od_src          = np.array(od_src_list,  dtype=np.int32),
    od_dst          = np.array(od_dst_list,  dtype=np.int32),
    od_dist         = od_dist_out,
    pair_idx        = pair_idx_arr,
    link_idx        = link_idx_arr,
    link_weight     = link_weight_arr,
    link_u          = np.array([u for u, v in link_list], dtype=np.int32),
    link_v          = np.array([v for u, v in link_list], dtype=np.int32),
    probit_n_passes = np.int32(N_PASSES),
    probit_cv       = np.float32(PROBIT_CV),
)
size_mb = os.path.getsize(PATHS_CACHE) / 1e6
print(f"Saved: {PATHS_CACHE}  ({size_mb:.1f} MB)")
print(f"  {n_pairs:,} OD pairs  {n_entries:,} entries  "
      f"{N_PASSES} passes  CV={PROBIT_CV}")
print(f"  {n_road} road nodes + {n_ext} external nodes = {n} total")
